18F/atf-eregs

- atf_eregs/templates/regulations/landing_479.html
> 479 landing page text

- atf_eregs/static/regulations/css/less/fonts.less
- atf_eregs/static/regulations/css/less/mixins.less
- atf_eregs/static/regulations/css/less/module/header.less
- atf_eregs/static/regulations/css/less/module/universal-landing.less
- atf_eregs/static/regulations/css/less/typography.less
Corresponds to 18F/regulations-site#27
> Commit @jeremiak's tweaks to regulations-site less files

- atf_eregs/settings/dev.py
Also turn on DEBUG mode
Resolves #71
> Turn off caching during development

- requirements.txt
> Pin requirements so we know what's in prod

- atf_eregs/templates/regulations/generic_landing.html
- atf_eregs/templates/regulations/landing_478.html
- atf_eregs/templates/regulations/landing_479.html
- atf_eregs/templates/regulations/landing_555.html
- atf_eregs/templates/regulations/landing_646.html
> Move shared content into separate template. Add 478, 555, 646 landing content

- RECRUITING.md
For use when pitching. Doesn't belong in atf-eregs, but we can move it once
there's a better home
> Some notes for recruiting new devs/designers

- .travis.yml
Resolves #94 
Hopefully Travis will start in a moment
> Simple CI script that just verifies _if_ this builds

- atf_eregs/static/regulations/css/less/module/universal-landing.less
Corresponds to 18f/regulations-site#45
The style sheets are overridden
> Corresponding change from -site

- atf_eregs/templates/regulations/landing_478.html
- atf_eregs/templates/regulations/landing_555.html
https://github.com/18F/atf-eregs/issues/137
> Add verification warning to 478 and 555 landing pages

- README.md
https://github.com/18F/atf-eregs/issues/141
> Specify Python 2.7 in docs

- atf_eregs/static/regulations/css/less/typography.less
> set background color on thead 

- atf_eregs/templates/regulations/landing_555.html
> 555 is now verified. No need for warning

- atf_eregs/static/regulations/css/less/module/header.less
- atf_eregs/templates/regulations/main-header.html
> Add BETA header/link

- atf_eregs/templates/regulations/landing_447.html
> Add landing page for 447

- atf_eregs/templates/regulations/landing_478.html
- atf_eregs/templates/regulations/landing_555.html
> Remove redundent intro paragraphs

- README.md
- manifest.yml
- newrelic.ini
- requirements.txt
Also, upgrades some other libs
For #202
> Add default New Relic

- atf_eregs/static/regulations/css/less/typography.less
Fixes sizing issues for datatables plugin
> styling changes for datatables

- atf_eregs/static/regulations/css/less/typography.less
Overflow handled within datatables wrapper.
> Use datatables plugin for horizontal scrolling

- README.md
Adding links to related repositories, and noting that the reader should set up a virtualenv using Python 2.7 and do one of the two Data steps.
> Adding implied steps to the readme for easier setup

- CONTRIBUTING.md
Also, tiny changes: 18F style sentence case for "Team Processes"; change a repeated "some" to "should".
> In CONTRIBUTING, note fork model rather than branching

- atf_eregs/settings/base.py
This likely requires updated data @tadhg-ohiggins @theresaanna Demo's data has already been updated. Live will be updated tonight.
> Turn on external citations

- atf_eregs/templates/regulations/landing_447.html
This is a small followup to https://github.com/18F/atf-eregs/pull/256 that addresses the hardcoded URL problem identified at https://github.com/18F/atf-eregs/issues/282
> Updating hardcoded URLs for 447 landing page experiment

- README.md
> Describe pip install -e

- .gitignore
- atf_eregs/templates/regulations/full_footer.html
- atf_eregs/templates/regulations/generic_landing.html
- atf_eregs/templates/regulations/landing_447.html
- atf_eregs/templates/regulations/landing_478.html
- atf_eregs/templates/regulations/landing_479.html
- atf_eregs/templates/regulations/landing_555.html
- atf_eregs/templates/regulations/landing_646.html
Add aria-label attribute to describe links that open in a new tab.
> 508 compliancy for external citations

- atf_eregs/templates/regulations/generic_landing.html
- atf_eregs/templates/regulations/landing_447.html
Reverts #256 and #287 while still applying #278 
Resolves #282
> Reverts the 447 landing page experiment

- README.md
Linking http://eregs.github.io/eRegulations/ and the Contributing guidelines.
> Noting useful background reading in the readme

- atf_eregs/templates/regulations/landing_479.html
Text and links have been checked by Andrew.
> Improving content of part 479 landing page

- atf_eregs/templates/regulations/landing_447.html
Text and links have been checked by Andrew.
> Improving content of part 447 landing page

- atf_eregs/templates/regulations/landing_478.html
Text and links have been checked by Andrew.
> Improving content of part 478 landing page

- atf_eregs/templates/regulations/landing_478.html
- atf_eregs/templates/regulations/landing_479.html
Fixing a couple of problems that @cmc333333 pointed out - thank you for catching these!
> Fixing link labels and ampersands in 478 and 479

- README.md
- docs/documentation.rst
- docs/index.rst
- docs/local_setup.rst
- docs/new_rule.rst
- docs/production_setup.rst
* Updated and slightly reorganized readme for clarity, including making sure the public domain status is very visible.
* Added short note about how to update the documentation, to encourage updating it.
* Some fixes for wording/links in the documentation.
> Revise documentation for clarity/usability

- atf_eregs/templates/regulations/landing_646.html
Text and links have been checked by Andrew.
> Improving content of part 646 landing page

- atf_eregs/static/regulations/css/less/module/custom.less
- atf_eregs/static/regulations/css/less/variables.less
Ignore commit message about svg icon sizing - that was done in -site
> Update drawer gray font to #666666 for 508 compliance.

- .travis.yml
- atf_eregs/management/commands/refresh.py
- atf_eregs/settings/base.py
- atf_eregs/settings/dev.py
- atf_eregs/settings/prod.py
- atf_eregs/sidebar.py
- atf_eregs/static/regulations/css/less/module/custom.less
- atf_eregs/static/regulations/css/less/variables.less
- atf_eregs/templates/regulations/sidebar/rulings.html
- atf_eregs/tests/sidebar_tests.py
- atf_eregs/wsgi.py
- requirements_test.txt
Looks like:
Though not strictly true, I'm going to say this PR relies on 18F/regulations-site#102 and #379. If so, this closes #376
> UI for rulings

- atf_eregs/templates/regulations/landing_555.html
> Adding links and context to part 555 landing page

- .about.yml
Basic metadata to fulfill https://github.com/18F/atf-eregs/issues/370 - can be improved further if people like!
> Add .about.yml file with project metadata

- eregs_extensions/atf_regparser/term_defs/__init__.py
Fixes some more of https://github.com/18F/atf-eregs/issues/339
> Add a couple of 'make' exclusions for 479 definitions.

- docs/production_setup.rst
- manifest_base.yml
- requirements.txt
> Serve with gunicorn instead of waitress

- CONTRIBUTING.md
> Add team process info to CONTRIBUTING

- requirements.txt
> Latest versions of Django, dj-database-url

- atf_eregs/wsgi.py
- requirements.txt
- requirements_test.txt
Already pushed to demo to verify that this works
> Remove new relic requirement

- atf_eregs/templates/regulations/about.html
Stop talking about us /
And predecessor work /
We are U S Gov.
https://github.com/18F/eregs-platform/issues/57
> Tweak intro paragraph text on about page.

- atf_eregs/static/regulations/css/scss/_variables.scss
A different gray /
Spirit of revolution /
More contrast is good.
https://github.com/18F/atf-eregs/issues/449
> Change defined term bottom border color

- atf_eregs/templates/regulations/landing_447.html
- atf_eregs/templates/regulations/landing_646.html
Add some searches to /
447 and 646 /
In the waning hours.
> Add sample search terms to 447 and 646 landing pages.

- atf_eregs/static/regulations/css/scss/_variables.scss
- atf_eregs/static/regulations/css/scss/module/custom/_typography.scss
- requirements.txt
Delete underline /
Replace with border and then /
Use inheritance.
> Use regulations-site upstream CSS for definition border color.

- .travis.yml
- compliance/component.yaml
- docker-compose.yml
- docs/customization.rst
- docs/local_setup.rst
- docs/production_setup.rst
- eregs_extensions/atf_regparser/layers.py
- eregs_extensions/atf_regparser/preprocs/__init__.py
- eregs_extensions/atf_regparser/tests/preprocessor_tests.py
- eregs_extensions/setup.py
- opencontrol.yaml
- requirements/test.txt
- requirements/web.txt
- system-security-plan.yml
1. Set up bandit in CI
2. Add/edit SSP and compliance documentation
3. Update version of -site
4. Bring docs up to date
> 4 sets of updates related to re-ATOing

- .travis.yml
- requirements/web.txt
- setup.cfg
These libs no longer need to be editable.
Visible in the demo environment.
> Update regulations-core and -site.

- .travis.yml
- devops/activate_then
- devops/compile_frontend.sh
- manifest_base.yml
I had a fresh checkout of the repo to set up the dev environment and hit a few snags along the way to deploying to a new environment.
> Bugs discovered when pushing to cloud.gov

- atf_eregs/management/commands/fetch_atf_resources.py
- atf_eregs/sidebar.py
- atf_eregs/tests/fetch_atf_resources_tests.py
- manifest_base.yml
Resolves #495 by fetching the ATF docs every hour.
Resolves #497 by using the new layer when displaying ruling content.
> Run fetch_resources every hour

- .gitmodules
- README.md
- atf_eregs/settings/base.py
- docker-compose.yml
- requirements.txt
- requirements_dev.txt
Using changes upstream, we now have a postgres for search and updated styles for the sidebar.
Should resolve #475, #499, and part of #500
> Bump dependencies for pgsql search and sidebar tweaks

- .circleci/config.yml
- devops/activate_then
- docker-compose-circle.yml
I squashed the commits from the work-in-progress branches and made another branch.
> Another Circle CI branch

- atf_eregs/templates/regulations/landing_478.html
Each state issues some /
And ATF combines them /
Instance thirty-two.
> Add link to State Laws and Published Ordinances on 478 landing page.

- eregs_extensions/atf_regparser/term_defs/__init__.py
[Continuation of https://github.com/18F/atf-eregs/pull/541 ]
> Ignore “states” in 555 and 646 when it's part of “United States”

- atf_eregs/templates/regulations/landing_447.html
- atf_eregs/templates/regulations/landing_478.html
- atf_eregs/templates/regulations/landing_555.html
- atf_eregs/templates/regulations/landing_646.html
Per the list in #509. Should close #509.
> Add "Additional Links" to part-specific pages.

- requirements.txt
> Update requirements file, too.

- atf_eregs/templates/regulations/landing_478.html
I think this should be
En eye see be ess, but that
Is harder to say.
> Add link to NICS to section 478 landing page (issue 564).

- atf_eregs/settings/base.py
- atf_eregs/templates/regulations/landing_478.html
* Add link to NICS to section 478 landing page #565
> Create new release

- .gitmodules
- requirements.txt
> Bump regulations to 8.4.1.

- .gitmodules
- atf_eregs/templates/regulations/landing_478.html
- requirements.txt
> Deploy #567
