18F/atf-eregs

- .cfignore
- .gitignore
Make Git ignore compiled/ and frontend_build/ directories; split out .cfignore and make CloudFoundry ignore the frontend_build/ directory but not the compiled/ directory.
> Separate .gitignore and .cfignore

- atf_eregs/settings/base.py
- atf_eregs/templates/regulations/about.html
- requirements.txt
As none of the ATF regs appear to have these features, we should avoid mentioning them about the about page.
Makes use of the `django-overextends` library to reuse most of the about template.
Resolves #45
> Remove text about SxS and interpretations from about page

- .cfignore
- .gitignore
- README.md
- atf_eregs/settings/base.py
- atf_eregs/settings/dev.py
- manage.py
Depends on 18F/regulations-site#32
* Adds 'compiled' to the list of static directories to search for files
* Defaults the port the app looks at for reading from the API to 8000
* Allow a local_settings file to override `base`
* Update README
> Settings and README update

- atf_eregs/static/regulations/css/less/mixins.less
- atf_eregs/static/regulations/css/less/module/about.less
- atf_eregs/static/regulations/css/less/module/header.less
- atf_eregs/static/regulations/css/less/module/universal-landing.less
1. Account for the hero text color on the "About" page
2. Change the default and bold font weights
3. Set the link color to a brighter blue, save in the header
Resolves #43 and #41
> Style tweaks

- atf_eregs/static/regulations/css/less/typography.less
Changed table layout to auto to prevent table headers from being squished. Made the main content div scrollable horizontally to accommodate larger tables.
> Squished table headers fix.

- requirements.txt
There's a security vulnerability in Django 1.8.7, so upgrade it. The vulnerability doesn't affect our usage, but better to stay up to date.
Thanks Gemnasium!
> Update django, whitenoise

- system-security-plan.yml.md
Leave the branch `authority-to-operate` around if you would for now.
> Temp system security plan before incorporation into compliance masonry

- atf_eregs/static/regulations/css/less/module/header.less
Was
Now
"About" is in hover state in both screenshots
Resolves #146
> Tweak colors so that the mobile header looks okay

- atf_eregs/static/regulations/css/less/module/header.less
- atf_eregs/templates/regulations/main-header.html
> Tweaks to 'beta'

- atf_eregs/settings/base.py
Removes SxS and interpretations, which aren't present in ATF regs
The sidebar config won't have an impact until 18f/regulations-site#59 is merged
> Configure ATF layers

- atf_eregs/templates/regulations/generic_landing.html
- atf_eregs/templates/regulations/landing_447.html
Here's a work in progress to demonstrate a few ideas - this takes the [current page for part 447](https://atf-eregs.18f.gov/447) and makes some changes to make it easier to understand for readers (#227):
* The intro sentence briefly summarizes the impact of the regulation, speaking directly to the reader with ordinary language.
* The list of topics notes the most important sections of the regulation and links directly to those items.
* The legal disclaimer links to the resources it mentions, so that readers can easily figure out how to get an official legal version if they need one.
* The sidebar includes links to relevant contact information, permit application forms, and related tools (e-CFR, a Federal Register search for the title of the regulation, and a Regulations.gov search for the …
> Example of a regulation landing page with extra context

- atf_eregs/templates/regulations/generic_landing.html
This is a simple change to address feedback from ATF (https://github.com/18F/atf-eregs/issues/262) that a more straightforward title for the legal disclaimer would help readers.
> Update "Trust, but verify" to "Legal limitations of this tool"

- atf_eregs/settings/prod.py
We were using an outdated elastic search connector from cloud.gov. In
switching to the recommended version, we discovered the key in the VCAP config
is slightly different. Account for both by using a substring match
> Use different elastic search config

- atf_eregs/management/commands/refresh.py
- manifest.yml
- requirements.txt
Add a new management command that runs migration and rebuilds the search
index if not running on cloud.gov or running on the 0th instance on
cloud.gov.
Related to #199.
A few notes:
* This uses `py-cfenv` to parse the cloud.gov environment variables. Parsing them by hand is simple, and it's already happening here, but IMO it's still worth using a separate tool to cut down repetitive tasks. Plus, I'm the maintainer. Anyway, happy to revert if the preference is for fewer external libs.
* The proposed `refresh` management task doesn't take any arguments, since my intention is for it to only get used on cloud.gov. I can add the `--fake-initial`, `--noinput`, and `--remove` flags if that would be useful.
@cmc333333
> Migrate and refresh on 0th instance only.

- README.md
- atf_eregs/settings/base.py
- atf_eregs/settings/prod.py
- atf_eregs/wsgi.py
- manifest.yml
- manifest_base.yml
- manifest_dev.yml
- manifest_prod.yml
- requirements.txt
Get credentials from user-provided service.
* Document user-provided service
* Set basic auth credentials from service
* Initialize new relic manually from service
* Clean up a few flake8 warnings
Notes:
* It's kind of ugly, but setting the basic auth credentials in `settings.py` seems to work. The issue is that regulations-core tries to pull the creds from the environment, but this patch proposes to get them from a user-provided service instead.
* I don't have permission to deploy this, so it wouldn't be entirely surprising if it doesn't quite work. If this looks roughly correct and I can get permission, I'll verify that it actually works.
@cmc333333
> Issue 63 user provided service

- README.md
[Resolves #284]
This doesn't actually do anything--it's just a suggestion to use `cf zero-downtime-push` instead of `cf push`. If we decide to deploy from CI (which would be great!), we'd update the Travis config to install `autopilot` and run `cf zero-downtime-push`.
This might also be a good time to add a script that wraps some cloud.gov boilerplate. On FEC, we're using `invoke` (what used to be the task runner in fabric) so that running `invoke deploy --space dev` effectively runs `cf target -o fec -s dev` and `cf zero-downtime-push fec manifest_dev.yml`. What do you think about something like that @cmc333333 and @tadhg-ohiggins?
> Document zero-downtime deploys with autopilot.

- eregs_extensions/extend_regparser/extensions.py
- eregs_extensions/extend_regparser/preprocs/__init__.py
- eregs_extensions/setup.py
- requirements.txt
This creates a home for extensions specific to the ATF, such as a regulations-processor preprocessor for US Code extracts. See https://github.com/18F/regulations-parser/pull/177 for how it integrates with regulations-parser.
> ATF-specific regulations-parser extensions.

- manifest_base.yml
- manifest_prod.yml
[Resolves #360]
@cmc333333 I'm guessing we only want to scale up to multiple instances for production, but if that's not right, I'll move the `instances` key to `manifest_base.yml`.
> Include instances and domains in manifests.

- atf_eregs/templates/atf_eregs/poster_wrapper.html
This subtemplate provided some logic on which type of li markers to use. We no
longer use the browser provided li markers, however, so this isn't needed any
longer.
> Remove ol-tag.html inclusion

- atf_eregs/templates/regulations/landing_447.html
- atf_eregs/templates/regulations/landing_478.html
- atf_eregs/templates/regulations/landing_479.html
Small changes to improve the right sidebar links to relevant search results on regulations.gov and federalregister.gov for 447, 478, and 479.
> More precise links to Regulations.gov and FR for landing pages

- eregs_extensions/atf_regparser/term_defs/__init__.py
> Exclusions for 447 definitions

- docs/customization.rst
An effort at an incrementally easier-to-understand explanation of the relationship between content in the shared libraries and content in the ATF-specific repository.
> Explaining templates a little bit more in the docs

- requirements.txt
Prior to 0.5.2, py-cfenv returned instance index as a string, but the
`refresh` management command (correctly) expects an integer. This patch
updates to the latest version of py-cfenv, which fixes this behavior.
This is why migrations didn't run on push--thanks @cmc333333 for catching.
#thatfeelingwhen you forget the interface on your own library
#lulz
> Update to latest py-cfenv.

- eregs_extensions/atf_regparser/tests/layers_tests.py
- eregs_extensions/atf_regparser/tests/preprocessor_tests.py
- eregs_extensions/extensions-outline.rst
Per eregs/regulations-parser#214, use the `regparser` namespaced test
libraries
> Prefer test_utils versions of libraries

- eregs_extensions/atf_regparser/layers.py
- eregs_extensions/atf_regparser/tests/layers_tests.py
This is holding up the Python3 version of regulations-parser
> Add Python3 support

- atf_eregs/static/regulations/css/less/module/custom/landing.less
Don't need the z-index anymore as the div comes before the text that is placed
on top of it. This regression arose due to setting a white background instead
of none (transparent).
Resolves eregs/notice-and-comment#404
> Fix reg landing images

- atf_eregs/sidebar.py
We modified the signature of a method called in ATF-eRegs. Tests did not catch
it as the relevant library is mocked out.
Resolves #434
> Fix ATF Rulings

- atf_eregs/settings/base.py
- atf_eregs/settings/dev.py
- atf_eregs/settings/prod.py
- atf_eregs/sidebar.py
- requirements.txt
- requirements_test.txt
As we make a big shift to SASS come version 6.0.0, we will need to update
downstream dependencies (ATF, FEC, EPA, etc.) one at a time. By pinning ATF to
this working version, we can avoid incompatibilities. It may be worth pinning
-core as well, but I'll kick that can down the road until it's necessary.
Resolves 18F/eregs-platform#20
> Pin -site version

- atf_eregs/static/regulations/css/scss/module/custom/_about.scss
For regulation timeline explanation image #3 on about page, use multiple-specificity CSS class rather than element.class specificity.
Addresses https://github.com/18F/atf-eregs/pull/443#pullrequestreview-952457
> Minor CSS tweak

- atf_eregs/static/regulations/css/scss/_variables.scss
- atf_eregs/static/regulations/css/scss/module/custom/_typography.scss
So it turns out that / 
`$gray_light` was used in a lot /
Of different places.
> Narrow change for defined term underlines to _only_ affect those colors.

- atf_eregs/settings/base.py
Per [Cloud Foundry documentation](https://docs.cloudfoundry.org/running/apps-enable-diego.html#app-code) use of `$VCAP_APP_HOST` and `$VCAP_APP_PASSWORD` are incompatible with newer (Diego-based) Cloud Foundry deployments. This change makes this repository forward compatible with the new cloud.gov environment deployment in AWS GovCloud.
> Cloud Foundry forward-compatibility

- .bandit
- .travis.yml
- eregs_extensions/atf_regparser/preprocs/__init__.py
- eregs_extensions/atf_regparser/tests/preprocessor_tests.py
- eregs_extensions/setup.py
- requirements/test.txt
- setup.cfg
Turns out, we haven't been testing, which meant that #456 broke a parsing plugin without us know. This fixes the plugin and makes sure we're testing.
> Fix testing & plugin errors

- .about.yml
- README.md
- deploy.sh
- docs/local_setup.rst
Tenant apps use `app.cloud.gov` on Govcloud as the default domain
> Change docs to point to the new app domain in govcloud

- requirements/prod.txt
- requirements/web.txt
A security update to Django was the impetus, but none of the changelogs
indicated issues with the other libs, so why not update them too. Appears to
work okay on demo.
> Upgrade several dependencies

- .gitignore
- .gitmodules
- devops/activate_then
The `activate_then` script had been checking out a specific version of -site
and -core on its first run and warning users if they were out of date. Git
provides much of this functionality already with git submodules, so use them
instead. Submodules also simplify updates, bringing the user to later versions
if there isn't a conflict.
This only affects the -site and -core checkouts as the -parser's docker image
doesn't include the git submodule info.
This should resolve #482, and should probably go in before #483. Users may need to
```sh
rm -rf eregs_libs
```
to see these updates going forward (and git won't clobber existing checkouts).
> Replace custom dev scripts with git submodules.

- devops/compile_frontend.sh
Django will look first in the `compiled` directory (then in the
regulations-site dirs) when searching for a static file. This is the correct
behavior when running the application, but not when we're building the
frontend (i.e. when we're filing that `compiled` directory). We should clear
out `compiled` earlier in the build script to accommodate this need.
> Clear copied frontend *before* collectstatic.

- .gitmodules
- requirements.txt
- requirements_dev.txt
This finishes up the Python side of #472 by upgrading the remaining Python libs. Most interesting is probably `requests`, which has many fewer dependencies now.
> Update remaining Python libs

- atf_eregs/atf_resources.py
- atf_eregs/management/commands/fetch_atf_resources.py
- atf_eregs/settings/base.py
- atf_eregs/tests/atf_resources_tests.py
- eregs_extensions/devops/activate_then
- requirements.in
- requirements.txt
- requirements_dev.txt
We have been generating ruling data in an extension to the parser. This clones most of that logic to generate a layer as a django management command so we can run it separately from the parser. @tadhg-ohiggins what do you think about the types here? I didn't run mypy, but was hoping they conveyed meaning a bit better.
Should resolve #489
> Add script to build "atf-resources" layer

- atf_eregs/settings/base.py
- docker-compose.yml
Currently, we only attach postgres to the running ATF instance if we run
`dev-with-db` (otherwise, we're running with the live ATF data, skipping the
SQLite-based local API). As we test a postgres-based search, we need to have
Postgres running (even if it's not actively used).
This accomplishes that by using a specific env variable to signify that we
want to use the live data (rather than just testing for a database
connection).
> Always attach postgres.

- atf_eregs/settings/base.py
- atf_eregs/sidebar.py
- atf_eregs/static/regulations/css/scss/module/_custom.scss
- atf_eregs/static/regulations/css/scss/module/custom/_atf-resources.scss
- atf_eregs/templates/regulations/sidebar/atf-resources.html
This adds the templates and styles to display the "Related documents" sidebar widget. For the time being, it starts opened and is an _addition_ to the Rulings heading. Once this one is all good, we can delete the Rulings widget.
Looks like:
> Related documents UI

- atf_eregs/atf_resources.py
- atf_eregs/related-docs.yml
- atf_eregs/sidebar.py
- atf_eregs/templates/regulations/sidebar/atf-resources.html
- atf_eregs/tests/atf_resources_tests.py
- atf_eregs/tests/sidebar_tests.py
This builds on #521 to use realistic data. It encodes a sample data file into Yaml (to create what we're anticipating from the ATF API), and uses that to send data to the UI.
> Related documents backend replacement

- atf_eregs/management/commands/refresh.py
When we start our instances in cloud.gov, we run a custom "refresh" management
command. This had been rebuilding the search index, but that broke when
switching to the Postgres-backed search. This is currently preventing us from
deploying.
> Run rebuild_pgsql_index instead of haystack.

- .circleci/config.yml
- devops/combine_frontend_sources.sh
- devops/compile_frontend.sh
- docker-compose-circle.yml
For now, building the frontend in Circle acts as a smoke test that we haven't broken anything. Soon, we'll use the UI when deploying.
As Circle doesn't allow mounting the local file system, this moves logic around a little bit. We had had a `compile_frontend.sh` script running in the host, shuttling files around. This moves those steps into a container so they'll run in Circle (and locally).
> Build the UI in Circle

- atf_eregs/templates/regulations/sidebar/atf-resources.html
We reuse the existing JS logic to start this content closed; it already
degrades for non-JS users nicely.
JS users see
Non-JS users see
Should resolve #500
> Start "Related documents" groups collapsed.

- manifest_prod.yml
We hadn't actually deployed to production after adding the regulations.atf.gov
domain, so we were missing a route in the production manifest.
> Add new domain to cloud.gov manifest.

- .gitmodules
- atf_eregs/settings/base.py
- atf_eregs/static/regulations/css/scss/module/custom/_typography.scss
- requirements.txt
By upgrading, we resolve some search issues and a print CSS tweak. This should resolve #513
The rank allows us to find results for "exploder combatant" (two very disjoint, one-use words) in 447. 
Headers looks like:
> Bump versions of upstream libs

- eregs_extensions/atf_regparser/term_defs/__init__.py
Some definitions /
Aren't always relevant. /
Just look straight ahead.
Addresses #536 via an exclusion for “United States” when adding term definitions to 478.
> Ignore the term “states” in 478 when it's part of “United States”.

- .gitmodules
- atf_eregs/static/regulations/css/scss/module/custom/_header.scss
- devops/deps_ok_then
- requirements.txt
This should resolve #384,  #472, #510, #514, #516 by pulling in the latest version of `regulations`.
Effective date looks like
> Pull in upstream, add styles for effective date

- .circleci/config.yml
The working directory isn't carried into the deployment phase of CircleCI. Or at least, that's my speculation.
Setting the working dir explicitly resolves either way.
> Fix deploys

- atf_eregs/templates/regulations/generic_universal.html
- atf_eregs/templates/regulations/main-header.html
Not everything is /
About us; the ants and birds /
Toil on in the sun.
Changes the home page to be less about eRegs and more about ATF-specific aspects. Also changes the upper-left text on every page from “eRegulations” to “ATF eRegulations”.
> Copy changes to home page

- atf_eregs/settings/prod.py
- docker-compose.yml
- requirements.in
- requirements.txt
- requirements_dev.txt
These two tweaks aren't really related other than being referenced in the same settings file.
This removes Elastic libraries as they are not needed any longer (we switched to Postgres for full-text search).
It also limits the cache timeout to an hour (to ensure relatively quick turn around for ATF data updates).
> Remove Elastic libs, limit cache timeout

- requirements.txt
- requirements_dev.txt
Django 1.11.5 fixes a security issue when running with DEBUG active. That
doesn't affect prod, but best to bump everything anyway.
Changelog:
https://docs.djangoproject.com/en/1.11/releases/1.11.4/
https://docs.djangoproject.com/en/1.11/releases/1.11.5/
> Bump django.

- manifest_base.yml
- manifest_dev.yml
- manifest_prod.yml
We share a cloud.gov memory allocation between our dev and prod environments.
Right now, we have 512M free to work with so that we can perform blue-green
deploys. Unfortunately, this means that when dev and prod environments deploy
at the same time, they _both_ try to eat that 512M, leading one to fail.
This resolves by staggering their auto-deployment by one hour.
> Stagger deploys.

- atf_eregs/settings/base.py
Test on demo site
Before testing production.
So say the seagulls.
Once we merge this to master we can see how the new URL works on demo.
> Update ATF API URL to point to their demo server, version 1.1

- atf_eregs/settings/base.py
TLAs for days.
ATF goes one point one.
We should do the same.
Updates the URL we use for the ATF related document API to `1.1`.
This PR uses their production URL. This should not be merged until we've tested their staging URL (which we don't have yet).
> Update ATF API URL to 1.1.
